### ISSUE TITLE
List modules

### ISSUE THREAD

**Issue by be2n** [bringyourownideas/silverstripe-maintenance#31]
As a CMS user
I want to know what modules are part of my site build 
So that I can understand how the feature/ functionality sets of the site are provided

## Acceptance criteria

- Module is listed in plain English (for example "Translatable" instead of silverstripe/translatable)
- Module listing has a short description of the functionality
- Meets the SilverStripe commercially supported module standard
- Has unit tests (see above)
- The existing functionality in this module is converted to a "Report", rather than a standalone ModelAdmin
- The list only shows SilverStripe modules
- The module doesn't **rely on** filesystem commands, but uses Composer packages to gather required data as much as possible

## Tasks

- [x] Write this functionality for SilverStripe 3 (see upgrade to 4 at #42)
- [x] Convert from a ModelAdmin into a Report
- [ ] Bring up to the SilverStripe commercially supported module standard (incl. unit tests, code style, documentation)
- [x] Implement the Composer PHP SDK and Packagist API as required to use this functionality

Designs: https://projects.invisionapp.com/share/ASGU6A7RT8U#/screens/291050684
