### ISSUE TITLE
List module version 

### ISSUE THREAD

**Issue by be2n** [bringyourownideas/silverstripe-maintenance#33]
As a Product Owner
I want to know what version of each module
So that I can have a more informed discussion with my developers about upgrade decisions

## Acceptance criteria

- [x] The currently installed version of each module used is listed
- [x] The most current version of the module is listed 
- [x] Next 'safe' stable version available is listed

Designs: https://projects.invisionapp.com/share/ASGU6A7RT8U#/screens/291050684

## Tasks

- [x] Migrate silverstripe-composer-verisons model into silverstripe-maintenance module: https://github.com/bringyourownideas/silverstripe-maintenance/issues/46
- [x] Convert composer-update-checker module's model to an extension: https://github.com/bringyourownideas/silverstripe-composer-update-checker/issues/25
- [ ] Replace constraint checking with composer/semver: https://github.com/bringyourownideas/silverstripe-composer-update-checker/issues/23
- [ ] Determine next safe version: https://github.com/bringyourownideas/silverstripe-composer-update-checker/issues/24

**Comment by robbieaverill** [comment]
Main pull request is at https://github.com/bringyourownideas/silverstripe-composer-update-checker/pull/28
