### ISSUE TITLE
Show a date stamp somewhere for when report was last generated

### ISSUE THREAD

**Issue by clarkepaul** [bringyourownideas/silverstripe-maintenance#67]
## AC
* The report should have a visible date for when the report was last updated. 
* When the report is refreshed/updated (when the "Check for updates" button is clicked) the date stamp should be able to attract the users attention to the fact the report update is complete. eg. Turns green or background has visible change. 
* The date stamp only need to be implemented for SS4 version of the module (excludes SS3)

## Tasks
* [x] Design to be provided by @sachajudd
* [x] Reassess and adjust effort required (story points) based on designs provided
* [x] Implementation for SS4 only
* [x] Time stamp is captured in the generated CSV file
* [x] Design review

## Notes
We (designers) are open to see what possibilities we have in regards to a loading state for the "Check for updates" button in the SS4 version—do we use the three dots loading indicator as per main actions in the Pages section or whether a spinning icon is easier to implement in this situation. Do some investigation and get back to us with whats possible before making a PR.

**Comment by sachajudd** [comment]
Design examples as below:
Note the text change from "Last updated" to "Updated". 
Any questions happy to chat 🙂 

![last updated](https://user-images.githubusercontent.com/24258161/40759097-9cdcfd64-64e4-11e8-9116-bdb1d5446de7.png)

**Comment by robbieaverill** [comment]
I see there's a new A/C added: "Time stamp is captured in the generated CSV file" - the CSV filename has the date in it by default, is that enough?

**Comment by sachajudd** [comment]
Does the CSV file have the time the report was downloaded or the time it was last updated (generated) in the CMS?  Example: you generated it on the 21/05/18 and you downloaded the CSV on the 31/05/18.

**Comment by robbieaverill** [comment]
Nope - it'd be tricky to add that to a CSV which is essentially a data extract. We could raise an enhancement on the framework to include the time by default maybe?
