### ISSUE TITLE
Track core release on addons.silverstripe.org call

### ISSUE THREAD

**Issue by chillu** [bringyourownideas/silverstripe-maintenance#70]
This is a lightweight way to keep track of SilverStripe adoption by version number. While we're planning wider tracking to cover this use case, it's not going to be deployed as quickly into sites as this module. By sending the `silverstripe/framework` version number, we get a good indication of the adoption rate. `silverstripe/recipe-core` won't give us that coverage (isn't used everywhere). 

Note that by only tracking the version number without a domain or unique identifier attached, we can't get a metric like "X sites are on 4.x". But we can at least say "X percent of calls to this API are made from 4.x sites". This is a compromise to keep tracking anonymous in this context.

## Tasks/pull requests

- [x] Gather the silverstripe/framework version when performing the API call to addons.silverstripe.org (see #41) - PR #73
- [x] Include it as a request header in the GET call - PR #73
- [x] Add data model as an audit metric to addons.silverstripe.org, logging each incoming header value - PR https://github.com/silverstripe/addons.silverstripe.org/pull/194

**Comment by ScopeyNZ** [comment]
See #73 and silverstripe/addons.silverstripe.org#194 🙂

**Comment by chillu** [comment]
🎉
